name: Deploy React App to Firebase Hosting

on:
  push:
    branches:
      - master

env:
  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  PUBLIC_DIRECTORY: build

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install --node-version '16'

    - name: Build React app
      run: npm run build --node-version '16'

    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        projectId: ${{ env.FIREBASE_PROJECT_ID }}
        repoToken: ${{ env.FIREBASE_TOKEN }}
        entryPoint : ${{ env.PUBLIC_DIRECTORY }}
